---
- block:

  - name: Restart nginx
    action: service name=nginx state=restarted

  - name: update tzdata
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

  become: yes
  become_user: root
